export const REQUEST_VALIDATION_ERROR_CODES = {
  INVALID_BODY: 'INVALID_BODY',
  INVALID_TOTAL: 'INVALID_TOTAL',
  INVALID_ITEMS: 'INVALID_ITEMS',
  INVALID_ADDRESS: 'INVALID_ADDRESS',
  INVALID_PHONE: 'INVALID_PHONE',
  INVALID_PUBLISH_TO_ALL: 'INVALID_PUBLISH_TO_ALL',
  INVALID_SOURCE_ALL_ID: 'INVALID_SOURCE_ALL_ID',
  INVALID_CATEGORY: 'INVALID_CATEGORY',
  INVALID_PLAN_ID: 'INVALID_PLAN_ID',
  INVALID_PAYMENT_REFERENCE: 'INVALID_PAYMENT_REFERENCE',
  INVALID_PROVIDER: 'INVALID_PROVIDER',
} as const;

export type RequestValidationErrorCode =
  (typeof REQUEST_VALIDATION_ERROR_CODES)[keyof typeof REQUEST_VALIDATION_ERROR_CODES];

export const API_COMMON_ERROR_CODES = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  MEMBERSHIP_REQUIRED: 'MEMBERSHIP_REQUIRED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  AI_BUDGET_USER_QUOTA_EXCEEDED: 'AI_BUDGET_USER_QUOTA_EXCEEDED',
  AI_BUDGET_GLOBAL_QUOTA_EXCEEDED: 'AI_BUDGET_GLOBAL_QUOTA_EXCEEDED',
  AI_BUDGET_DELAYED: 'AI_BUDGET_DELAYED',
} as const;

export type ApiCommonErrorCode =
  (typeof API_COMMON_ERROR_CODES)[keyof typeof API_COMMON_ERROR_CODES];

export type ApiErrorCode = RequestValidationErrorCode | ApiCommonErrorCode;
